name: Maven Clean Install Action
description: A composite action to ensure that code builds correctly

# Inputs
inputs:
  branch_name: 
    description: "Current Branch"
    required: true
    default: "main"
  sonarcloud_token:
       description: "Token For Sonarcloud"
       required: false
  sonarcloud_host_url:     
       description: "Sonarcloud Host URL"
       required: false
  sonarcloud_organization:
       description: "Organization Name on Sonarcloud "
       required: false
  sonarcloud_sources:
       description: "source folder"
       required: false   
  sonarcloud_projectKey:
       description: "Sonar project key"
       required: false
  sonarcloud_coverage_jacoco_xmlReportPaths:
       description: "Jacoco reports path"
       required: false
  sonarcloud_java_binaries:
       description: "Java binaries folder"
       required: false         
  sonarcloud_tests:
       description: "Java test folder"
       required: false   
       
runs:
  using: "composite" 
  steps:
      - name: Get Current Version
        shell: bash
        run: |
            echo "POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Print Version
        shell: bash
        run: echo "Current Version - ${{env.POM_VERSION}}"

      - name: Split version code
        uses: xom9ikk/split@v1.1
        id: splitVersion
        with:
          string: ${{env.POM_VERSION}}
          separator: -SNAPSHOT
          limit: -1

      - name: Set New Unique Version
        shell: bash
        run: echo "uniqueVersion=${{steps.splitVersion.outputs._0}}-${{github.event.inputs.feature_branch}}-SNAPSHOT" >> $GITHUB_ENV

      # The GitHub Actions workflow will automatically use the existing  global user.name configuration set on the developer's machine for any Git operations within the workflow. No additional configuration is needed in the workflow YAML file.
      - name: Commit & Push
        shell: bash
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git pull -p
          git checkout -b $FEATURE_BRANCH
          mvn versions:set -DnewVersion=${{env.uniqueVersion}} -DgenerateBackupPoms=false
          git commit -am "Draft: Update feature version to ${{env.uniqueVersion}}"
          git pull origin main
          git push -u origin $FEATURE_BRANCH

      - name: Create PR
        shell: bash
        if: env.PR_EXIST == 'false'
        run: |
          curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/repos/BasedNoobDevelopers/Noob-GitHub-Actions-POC/pulls \
          -d '{"title":"Draft - ${{env.FEATURE_BRANCH}}","body":"Draft","head":"${{github.repository_owner}}:${{env.FEATURE_BRANCH}}","base":"BasedNoobDevelopers:${{env.TRUNK_BRANCH}}"}'
