name: Maven Clean Install Action
description: A composite action to ensure that code builds correctly

# Inputs
inputs:
  branch_name: 
    description: "Current Branch"
    required: true
    default: "main"
  action_chosen:
    description: action chosen
    required: true
  TOKEN:
    description: "token"
    required: true  
       
runs:
  using: "composite" 
  steps:
      - name: Get Current Version
        id: getCurrentVersion
        shell: bash
        run: |
            echo "POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Print Version
        shell: bash
        run: echo "Current Version - ${{steps.getCurrentVersion.POM_VERSION}}"

      - name: Split version code
        uses: xom9ikk/split@v1.1
        id: splitVersion
        with:
          string: ${{steps.getCurrentVersion.POM_VERSION}}
          separator: -SNAPSHOT
          limit: -1

      - name: Set New Unique Version
        id: uniqueVersion
        shell: bash
        run: echo "uniqueVersion=${{steps.splitVersion.outputs._0}}-${{inputs.branch_name}}-SNAPSHOT" >> $GITHUB_OUTPUT

      # The GitHub Actions workflow will automatically use the existing  global user.name configuration set on the developer's machine for any Git operations within the workflow. No additional configuration is needed in the workflow YAML file.
      - name: Commit & Push
        shell: bash
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git pull -p
          git checkout -b ${{inputs.branch_name}}
          mvn versions:set -DnewVersion=${{steps.uniqueVersion.outputs.uniqueVersion}} -DgenerateBackupPoms=false
          git commit -am "Draft: Update feature version to ${{steps.uniqueVersion.outputs.uniqueVersion}}"
          git pull origin main
          git push -u origin ${{inputs.branch_name}}

      - name: Create PR
        shell: bash
        run: |
          curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ inputs.TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/repos/BasedNoobDevelopers/Noob-GitHub-Actions-POC/pulls \
          -d '{"title":"Draft - ${{inputs.branch_name}}","body":"Draft","head":"${{github.repository_owner}}:${{inputs.branch_name}}","base":"BasedNoobDevelopers":"main"}'
